services:
  astro-blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: astro-blog:1.0.0
    container_name: astro-blog
    restart: unless-stopped
    networks:
      - proxy-tier
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  proxy-tier:
    external: true
